config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homepage#index'
  resources :candidates, only: :show
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
# frozen_string_literal: true

class Candidate < ApplicationRecord
  has_many :jobs
  has_many :notes
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :candidate
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :candidate
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
# frozen_string_literal: true

class CandidatesController < ApplicationController
  def show
    @candidate = find_candidate
    @jobs = @candidate.jobs.order('created_at DESC')
    @notes = @candidate.notes
  end

  private

  def find_candidate
    Candidate.find(params[:id])
  end
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

class HomepageController < ApplicationController
  def index
    @candidates = Candidate.includes(:jobs, :notes).order(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/candidates/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header text-center">
      <h3><%= @candidate.name %></h3>
    </div>
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col">
            <ul class="list-group">
              <li class="list-group-item list-group-item-action active">Contact</li>
              <li class="list-group-item"><%= "Email: #{@candidate.email}" %></li>
              <li class="list-group-item"><%= "Phone: #{@candidate.phone}" %></li>
            </ul>
          </div>
          <div class="col">
            <ul class="list-gro§up">
              <li class="list-group-item list-group-item-action active">Jobs</li>
                <% @jobs.each do |job| %>
                  <li class="list-group-item">
                    <p><%= "#{job.name} - #{job.created_at.strftime('%Y, %b %d')}" %></p>
                  </li>
                <% end %>
            </ul>
          </div>
        </div>
        <ul class="list-group mt-4">
          <li class="list-group-item list-group-item-action active">Notes</li>
            <% @notes.each do |note| %>
              <li class="list-group-item">
                <p><%= note.content %></p>
              </li>
            <% end %>
        </ul>
      </div>
    </div>
    <div class="card-footer text-muted">
      <%= link_to 'All list', root_path, class: "btn btn-lg btn-block" %>
    </div>
  </div>
</div>

app/views/homepage/index.html.erb
<div class="container-fluid">
  <div class="card">
    <div class="card-header text-center">
      <h2>List of our candidates</h2>
    </div>
    <div class="card-body">
      <div class="table-responsive table-hover">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Jobs Count</th>
              <th>Notes Count</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @candidates.each do |candidate| %>
              <tr>
                <td><%= candidate.name %></td>
                <td><%= candidate.email %></td>
                <td><%= candidate.phone %></td>
                <td><%= candidate.jobs.count %></td>
                <td><%= candidate.notes.count %></td>
                <td><%= link_to 'View',  candidate_path(candidate), class: "btn btn-outline-secondary" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candidates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>